/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp_JNITest */

#ifndef _Included_cpp_JNITest
#define _Included_cpp_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cpp_JNITest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
